# Generated by Django 2.1.7 on 2019-08-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='area',
            field=models.CharField(default='강남구 역삼1동', max_length=100),
        ),
        migrations.AddField(
            model_name='blog',
            name='job_type',
            field=models.CharField(default='서비스', max_length=100),
        ),
    ]
