# Generated by Django 2.1.7 on 2019-08-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20190806_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='enddate',
            field=models.DateTimeField(null=True),
        ),
    ]
