# Generated by Django 2.1.7 on 2019-08-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_blog_enddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='userdate1',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='blog',
            name='userdate2',
            field=models.CharField(default='', max_length=10),
        ),
    ]
