# Generated by Django 2.1.7 on 2019-08-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_auto_20190807_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='age',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='call',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='condition',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='edu',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='blog',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='etc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='gender',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='blog',
            name='pay',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='plus',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='blog',
            name='time1',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='blog',
            name='time2',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
