# Generated by Django 2.2.4 on 2019-08-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='enddate',
            field=models.CharField(default='', max_length=10),
        ),
    ]
