# Generated by Django 2.2.4 on 2019-08-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='area',
            field=models.CharField(default='개포동', max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='job_type',
            field=models.CharField(default='매장관리', max_length=100),
        ),
    ]
