# Generated by Django 2.2.4 on 2019-08-20 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_auto_20190810_0332'),
        ('blogapp', '0007_auto_20190810_0345'),
    ]

    operations = [
    ]
